Document: jchat
Title: Debian jchat Manual
Author: <insert document author here>
Abstract: This manual describes what jchat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jchat/jchat.sgml.gz

Format: postscript
Files: /usr/share/doc/jchat/jchat.ps.gz

Format: text
Files: /usr/share/doc/jchat/jchat.text.gz

Format: HTML
Index: /usr/share/doc/jchat/html/index.html
Files: /usr/share/doc/jchat/html/*.html
